# Generated by Django 2.1.5 on 2019-05-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpAndDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(default=0)),
                ('up_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down', to='news.News')),
                ('up_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_num', models.IntegerField(default=0)),
                ('up_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
    ]
