# Generated by Django 2.1.5 on 2019-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_upanddown_upnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upnum',
            name='up_num',
            field=models.IntegerField(default=1),
        ),
    ]
