# Generated by Django 2.1.5 on 2019-05-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190507_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upanddown',
            name='up_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_news', to='news.News'),
        ),
        migrations.AlterField(
            model_name='upanddown',
            name='up_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upnum',
            name='up_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_num', to='news.News'),
        ),
    ]
