# Generated by Django 2.1.5 on 2019-05-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190507_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upnum',
            name='up_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_num1', to='news.News'),
        ),
    ]
