# Generated by Django 2.1.5 on 2019-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190507_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upnum',
            name='up_news',
        ),
        migrations.AddField(
            model_name='news',
            name='up_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='UpNum',
        ),
    ]
